//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        public int participation_ID { get; set; }
        public int p_sportsman_ID { get; set; }
        public int p_сompetition_ID { get; set; }
        public string result { get; set; }
        public string place { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Sportsman Sportsman { get; set; }
    }
}
