//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sportsman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sportsman()
        {
            this.Participations = new HashSet<Participation>();
        }
    
        public int sportsman_ID { get; set; }
        public int s_section_ID { get; set; }
        public string surname { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string growth { get; set; }
        public string weight { get; set; }
        public string achievement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participations { get; set; }
        public virtual Section Section { get; set; }
    }
}
